### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by idnwc** [Sivolen/NABS#2]
What username and password should I use to log in via the web interface?

**Comment by Sivolen** [comment]
Hi!
I use web authorization through active directory ldap, there are options in the config-example file (AD_ADDRESS="", AD_SEARCH_TREE="").  If it's not convenient for you, I can bypass and add the ability to log in with other methods?

**Comment by Sivolen** [comment]
Hi @idnwc !
I added local login and fixed bugs.
You need to do git pull
